"""Update to GUID for SQLite compatibility

Revision ID: 61d69807583e
Revises: 8741c62108dd
Create Date: 2025-11-25 22:12:35.665271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sys
from pathlib import Path

# Add backend directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from utils.db_types import GUID


# revision identifiers, used by Alembic.
revision: str = '61d69807583e'
down_revision: Union[str, None] = '8741c62108dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitcoin_historical_data',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('preco_eur', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('volume', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('market_cap', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bitcoin_data', 'bitcoin_historical_data', ['data'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_bitcoin_historical_data_data'), 'bitcoin_historical_data', ['data'], unique=True)
    op.create_table('pprs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('gestor', sa.String(length=100), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('taxa_gestao', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pprs_isin'), 'pprs', ['isin'], unique=True)
    op.create_index(op.f('ix_pprs_nome'), 'pprs', ['nome'], unique=False)
    op.create_table('ppr_historical_data',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('ppr_id', GUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor_quota', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('rentabilidade_acumulada', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ppr_id'], ['pprs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ppr_historical_data', 'ppr_historical_data', ['ppr_id', 'data'], unique=False, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ppr_historical_data', table_name='ppr_historical_data', postgresql_using='btree')
    op.drop_table('ppr_historical_data')
    op.drop_index(op.f('ix_pprs_nome'), table_name='pprs')
    op.drop_index(op.f('ix_pprs_isin'), table_name='pprs')
    op.drop_table('pprs')
    op.drop_index(op.f('ix_bitcoin_historical_data_data'), table_name='bitcoin_historical_data')
    op.drop_index('idx_bitcoin_data', table_name='bitcoin_historical_data', postgresql_using='btree')
    op.drop_table('bitcoin_historical_data')
    # ### end Alembic commands ###
